### ISSUE TITLE
OSC list output help

### ISSUE THREAD

**Issue by LionGartGithubPage** [maybites/blender.NodeOSC#13] opened 2021-07-21 22:01 UTC
Hello maybites,

First of all, I really love the add-on. I somehow found an issue when using the animation node side of the addon (Node messages). I can't send OSC from blender animation nodes. Are there any examples you can share. I would love to use blender as the source of OSC. I want to turn vector data from animation node to osc list. Is this even possible? Would really appreciate the help.

**Comment by maybites** [comment] 2021-07-22 09:07
If you could attach your blendfile, I can have a look at it. currently I don't plan for a tutorial, since I deem the node part obsolete - but your usecase might change my mind..

**Comment by LionGartGithubPage** [comment] 2021-07-27 04:55
Hello, there sorry for the late reply. I didn't expect you to reply so fast. I was spending some time using the addon and found a problem that I think is more important. I can send you the blend file containing a rig and a sample of the OSC format I am using.

**Comment by LionGartGithubPage** [comment] 2021-07-27 05:17
@maybites Right now my concern doesn't really focus on the first problem of couldn't get the output animnode to work anymore. It is now more focused on the actual way I want the addon to help me. I want to use it to receive OSC data from motion capture software. The OSC data have a certain format and I tried using your features to filter the data, but it seems that it can't recieve all the data at once. I believe opening the file will give a better understanding of the issue.

[https://github.com/LionGartGithubPage/files](url).  You can find the files here. Please just chat at any time if you would ask for more info if you feel that I am not that clear.

**Comment by LionGartGithubPage** [comment] 2021-07-27 05:24
![OSC_VMC - Copy](https://user-images.githubusercontent.com/77560129/127115561-0760eb07-f0e6-4790-abb5-3d1fe9997a18.png)


Here is the preview of the Blend file and how I use your addon. You can find the files here. https://github.com/LionGartGithubPage/files. Thank you for your time.

**Comment by maybites** [comment] 2021-07-29 07:28
> The OSC data have a certain format

can you post the format here?

**Comment by LionGartGithubPage** [comment] 2021-07-29 23:57
[Mop_Protokol - Copy.txt](https://github.com/maybites/blender.NodeOSC/files/6904235/Mop_Protokol.-.Copy.txt)
[VM_protokol_WithNodeOSC - Copy.txt](https://github.com/maybites/blender.NodeOSC/files/6904237/VM_protokol_WithNodeOSC.-.Copy.txt)
There are two types of formats. This is the same motion data. Just with a different format. Just in case you might want to inspect the format and try out things. I also have problem turning these float values to a degree either in Euler or quaternion . Maybe that resulted in the failed track.

**Comment by maybites** [comment] 2021-07-31 13:15
considering 

`'/Mop/BoneControl/foot_r', 14.41500473022461, 13.122965812683105, 0.08309781551361084, 0.020568735897541046, -0.4878200888633728, 0.3490883409976959, 0.7998414039611816`

assuming this structure: address posX posY posZ quatW quatX quatY quatZ

address: /Mop/BoneControl/foot_r
filter: <empty and not applicable - can only be used on arguments, not on the address itself>
datapath: bpy.data.objects['motion'].pose.bones["RightFoot"].rotation_quaternion
args[idx]: (3, 4, 5, 6)

considering

`['/VMC/Ext/Tra/Pos', 'RightHand', -0.2618580460548401, 1.021303653717041, -0.13908575475215912, 0.22606851160526276, -0.016798153519630432, 0.4424645006656647, 0.8676614761352539]`

assuming this structure: address bone-name posX posY posZ quatZ quatX quatY quatW

your settings seems to be correct.

I am not sure if datapath 'rotation_quaternion' works on bones just like this. On normal objects you HAVE to switch the rotation-type from 'XYZ-Euler' to 'Quaternion WXYZ' in order to work (I think), but on bones I don't see this possibility - but I am not familiar with bones..

**Comment by LionGartGithubPage** [comment] 2021-08-04 21:46
Thank you for your reply. After reading your comment I can say that I have input the correct input for the Node OSC setting. However everytime I start receiving OSC data only one slot of the Node OSC will work. If I have two or more addresses coming in only one slot address will move. If I am listening to two inputs such as the left arm and right arm. Only one arm will move. The weird thing is it work correctly one at the time. Please help me with this. Can Node OSC listen to multiple address at the same time? Using Max as source means the OSC only streamed one at the time like in your tutorial.

**Comment by maybites** [comment] 2021-08-05 08:21
can you provide me an example? ideally a blend file and a max patch..

**Comment by LionGartGithubPage** [comment] 2021-08-05 10:27
can I send you via email? I did upload the file here https://github.com/LionGartGithubPage/files. What do you mean by a max patch?

**Comment by LionGartGithubPage** [comment] 2021-08-05 10:41
The source of the osc data comes from this three 3d tracker program. If you like you can try installing and stream it from it.
https://digital-standard.com/threedpose/ThreeDPoseTracker_Win_x64_v0_2_0.zip. It is very easy to use. Just upload a video to make it work. But if you like I can send anything you like.

**Comment by LionGartGithubPage** [comment] 2021-08-05 10:48
Tell me if you like a quick guide to using the motion capture. I know it is a lot to ask of you. But I think using the application to stream the OSC will be the best way to show the problem. Thank you. I think it will just take 4 steps to set up.

**Comment by maybites** [comment] 2021-08-05 15:13
if you could provide a movie, that would be cool. So far I am unable to reproduce, nodeOSC seems to work as intended. but I will do more tests tomorrow.

**Comment by LionGartGithubPage** [comment] 2021-08-05 16:43
you can find the video here: https://github.com/digital-standard/ThreeDPoseTracker/tree/master/SampleVideo. For the steps.

1.extract the zip file and find the exe.
2. run the exe and it will open a window with a model and everything ready
![image](https://user-images.githubusercontent.com/77560129/128388217-72fb8fd8-e524-4d3d-81a9-05859d7ba010.png)

3.  Click on the Configuration button to set the OSC address. Please click the check box to activate and set the address.
![image](https://user-images.githubusercontent.com/77560129/128388318-29782587-648e-424c-9995-1e956606765b.png)

4. Click Apply button and close the pop-up window. Now just press the load movie button and select the video. It will run and sending OSC to the address

**Comment by LionGartGithubPage** [comment] 2021-08-05 16:48
Thank you for taking the time to do this. Please just tell me anything that you need to make it work. I know it is almost impossible to recreate the problem without using the actual source. I spend some time at the beginning working with Max OSC like in your tutorial and Node OSC works amazingly. It is only when I applied this source it seems to be unable to execute all the OSC at once.

**Comment by maybites** [comment] 2021-08-06 09:17
ok, I think I found the bug. My code filters repeating osc messages with the same address. This makes sense in order not to swamp blender in case of hight data throughput, but bites you now. I will add a flag to switch this on and off.

**Comment by maybites** [comment] 2021-08-06 10:29
this issue should be fixed with the new release: 

https://github.com/maybites/blender.NodeOSC/releases/tag/V2.3

**Comment by LionGartGithubPage** [comment] 2021-08-07 14:24
wow, really. Thank you. So now there is a toggle state for enabling repeating OSC data. I will check it out. Thank you for helping me out with this.

**Comment by maybites** [comment] 2021-08-08 09:48
Let me know if you can confirm the fix..

**Comment by LionGartGithubPage** [comment] 2021-08-10 22:41
Sorry I can seem to make it work. Is there a step I am missing?
![image](https://user-images.githubusercontent.com/77560129/128944054-c4ced16e-3285-4b3c-b664-01ae64758bb2.png)

**Comment by LionGartGithubPage** [comment] 2021-08-10 22:42
This time nothing happend. I check that the stream is coming in but nothing happened.

**Comment by LionGartGithubPage** [comment] 2021-08-10 22:46
Hello, I got it working. but just in case would you point out where the filter toggle you mentioned? In case I accidentally pressed it.

**Comment by maybites** [comment] 2021-08-11 07:26
Filter incoming...

**Comment by sirismyfirstname** [comment] 2022-01-16 04:05
Hello,

First of all, thank you for writing this program. 

Judging by the title of this thread I think I'm in the right place. I found a tutorial https://www.youtube.com/watch?v=ssVcU8xsRT8 that allows you to control Blender with Max/MSP via NodeOSC. Thing is, I basically want to do the opposite. I would like to control Max/MSP with Blender via NodeOSC.

After getting everything installed, it seemed pretty obvious what the steps to success would be but I'm getting no feedback of any kind in Max.

Thank you for your time

<img width="843" alt="Screen Shot 2022-01-15 at 11 02 01 PM" src="https://user-images.githubusercontent.com/24487777/149646817-844ed0cb-0659-4ccf-8b18-c6bdae987f95.png">

<img width="1679" alt="Screen Shot 2022-01-15 at 10 58 45 PM" src="https://user-images.githubusercontent.com/24487777/149646832-a804853a-1b17-44a6-8dc5-a57921ad1d7c.png">

**Comment by maybites** [comment] 2022-01-16 09:55
Did you create any custom output messages? I don’t see any in your screenshot.

On 16 January 2022 at 05:05:45, Sir Kay ***@***.***) wrote:

Hello,

First of all, thank you for writing this program.

Judging by the title of this thread I think I'm in the right place. I found a tutorial https://www.youtube.com/watch?v=ssVcU8xsRT8 that allows you to control Blender with Max/MSP via NodeOSC. Thing is, I basically want to do the opposite. I would like to control Max/MSP with Blender via NodeOSC.

After getting everything installed, it seemed pretty obvious what the steps to success would be but I'm getting no feedback of any kind in Max.

Thank you for your time





—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.  
You are receiving this because you were mentioned.

-.. --- -. - - .-. -.-- - --- ..-. .. -. -.. -- . .- -. .. -. --. .. -. . ...- . .-. -.-- - .... .. -. --.

::  Martin Fröhlich
::  http://maybites.ch
::  ++41 (0)76 479 26 34

::  Hönggerstrasse 2
::  8037 Zürich
::  Switzerland

**Closed as completed** 2022-12-01 21:24 UTC
